# Exported from Render on 2025-05-07T22:07:47Z
services:
- type: web
  name: AppFinancesControl
  runtime: docker
  repo: https://github.com/jodairnunes/AppFinancesControl
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: DATABASE_PASSWORD
    sync: false
  - key: DATABASE_USERNAME
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
